
tasks:
  - name: frontend
    before: |
      cd frontend
    init: |
      npm install
      npm run build
    command: |
      export FULLSTACK_BACKEND=`gp url 3001`
      npm run dev

  - name: backend
    before: |
      cd backend
    init: |
      npm install
    command: |
      export FULLSTACK_FRONTEND=`gp url 3000`
      npm start

vscode:
  extensions:
    - svelte.svelte-vscode